'use client';

import { useEffect, useState, useCallback } from 'react';
import { supabase } from '@/lib/supabaseClient';

interface CheckIn {
  created_at: string;
  mood: string;
  notes: string | null;
  energy_level: number;
  meaningfulness: number;
  stress_triggers?: string[];
  recovery_activities?: string[];
}

export default function SummaryPage() {
  const [checkins, setCheckins] = useState<CheckIn[]>([]);
  const [loading, setLoading] = useState(true);
  const [aiSummary, setAiSummary] = useState('');
  const [imagePrompt, setImagePrompt] = useState('');
  const [imageUrl, setImageUrl] = useState('');
  const [saved, setSaved] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    const fetchData = async () => {
      try {
        const oneWeekAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();

        const { data: checkinData, error: checkinError } = await supabase
          .from('checkins')
          .select('*')
          .order('created_at', { ascending: true })
          .gte('created_at', oneWeekAgo);

        if (checkinError) throw checkinError;
        if (!checkinData || checkinData.length === 0) {
          setCheckins([]);
          setLoading(false);
          return;
        }

        setCheckins(checkinData);

        const response = await fetch('/api/openai-proxy', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ checkins: checkinData }),
        });

        const result = await response.json();

        if (!result.summary || !result.imagePrompt) {
          throw new Error('AI failed to generate summary or prompt');
        }

        setAiSummary(result.summary);
        setImagePrompt(result.imagePrompt);
        setImageUrl(result.imageUrl || '');

        const { data: { user }, error: userError } = await supabase.auth.getUser();
        if (userError || !user) throw userError;

        const { error: insertError } = await supabase.from('moodboards').insert([
          {
            user_id: user.id,
            summary: result.summary,
            prompt: result.imagePrompt,
            image_url: result.imageUrl,
          },
        ]);

        if (insertError) throw insertError;

        setSaved(true);
      } catch (err) {
        console.error('Summary error:', err);
        setError('Something went wrong while generating your moodboard.');
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, []);

  const handleDownload = useCallback(() => {
    if (!imageUrl) return;
    const link = document.createElement('a');
    link.href = imageUrl;
    link.download = 'moodboard.png';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }, [imageUrl]);

  return (
    <main className="min-h-screen bg-gray-50 px-4 py-10 text-gray-800">
      <div className="max-w-2xl mx-auto space-y-8">
        <h1 className="text-3xl font-bold text-center">🎨 MoodBoard AI</h1>

        {loading ? (
          <div className="text-center py-12">
            <p className="text-gray-500 text-sm animate-pulse">Generating your insights...</p>
          </div>
        ) : checkins.length === 0 ? (
          <div className="text-center py-12">
            <p className="text-gray-500">No check-ins to summarize yet.</p>
          </div>
        ) : error ? (
          <div className="text-center py-12">
            <p className="text-red-500 font-medium">{error}</p>
          </div>
        ) : (
          <>
            {/* AI Summary Section */}
            <section className="bg-white rounded-xl shadow-sm p-6 space-y-3">
              <h2 className="text-xl font-semibold">🧠 AI Summary of Your Week</h2>
              <p className="text-gray-700 whitespace-pre-line leading-relaxed">
                {aiSummary}
              </p>
            </section>

            {/* Moodboard Visual */}
            <section className="bg-white rounded-xl shadow-sm p-6 space-y-3">
              <h2 className="text-xl font-semibold">🖼️ Visual Mood Snapshot</h2>
              <p className="text-sm text-gray-500">Prompt used: <span className="italic">{imagePrompt}</span></p>
              {imageUrl ? (
                <img
                  src={imageUrl}
                  alt="Moodboard generated by AI"
                  className="w-full h-64 object-cover rounded-lg shadow"
                />
              ) : (
                <p className="text-gray-400 italic">No image generated</p>
              )}
            </section>

            {/* Actions */}
            <div className="text-center mt-6 space-y-3">
              <button
                onClick={handleDownload}
                className="inline-flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white font-semibold px-6 py-3 rounded-lg transition focus:outline-none focus:ring-2 focus:ring-blue-400"
              >
                📤 Download MoodBoard
              </button>
              {saved && (
                <p className="text-sm text-green-600 font-medium">
                  ✅ Moodboard saved to your journal
                </p>
              )}
            </div>
          </>
        )}
      </div>
    </main>
  );
}
